### ISSUE TITLE
DictionaryHelper.GetValuesDictionary Problem

### ISSUE THREAD

**Issue by happtim** [fgilde/Nextended#2]
The parameter removeDefaults is ineffective when retrieving property values using `GetValuesDictionary` in `DictionaryHelper`. The code `typeof(T).GetProperty(pair.Key, flags)?.GetValue(newInstance) != pair.Value` can only determine value types. However, the values returned by `GetValuesFunc` are all boxed values, such as object(int).

Is replacing object.equals the solution to the problem?

**Comment by fgilde** [comment]
maybe you are right. I will have a look at it

**Comment by fgilde** [comment]
its changed in 8.0.15
